### ISSUE TITLE
PostgreSQL 14 support

### ISSUE THREAD

**Issue by devrimgunduz** [lzlabs/pg_statement_rollback#2]
Hi,

Latest release builds against v14, but regression tests fail. Logs are attached. Can you please take a look? We started packaging for v14. Thanks! Devrim

[regression.diffs-pg_statement_rollback.txt](https://github.com/lzlabs/pg_statement_rollback/files/6599228/regression.diffs-pg_statement_rollback.txt)

**Comment by darold** [comment]
Thanks Devrim, yes I will fix that asap.

**Comment by darold** [comment]
That should work now with latest release v1.2.

**Comment by devrimgunduz** [comment]
Hi,

Thanks! Regression tests are still failing and also crashing postmaster. See the logs above. Thanks!

**Comment by darold** [comment]
Devrim, does the tests you are running is on a PG compiled with assert? Documentation warn about that `When compiled with assert enabled (--enable-cassert) PostgreSQL will crash when the extension is used. This problem have been reported on hackers in thread https://www.postgresql-archive.org/Issue-with-server-side-statement-level-rollback-td6162387.html I can not propose external solution for that.  I have also proposed a hook that will allow a transparent implementation of rollback at statement side in patch https://commitfest.postgresql.org/33/2860/ which will do not suffer of this problem but the least we can say is that it does not fascinate. The extension that could work with this hook is here https://github.com/darold/pg_statement_rollbackv2.

This is a bit daunting because it would extend the possibilities of PostgreSQL in a non-intrusive way. However for the current extension if you are running your test on PG compiled with assert this is a no go, it can not be fixed.

**Comment by devrimgunduz** [comment]
Hi @darold ,

Fair enough, so I'm closing this issue. Thanks a  lot!
